# Generated by Django 3.2.7 on 2021-10-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theblog',
            old_name='author_name',
            new_name='author',
        ),
    ]
