# Generated by Django 3.2.7 on 2021-10-20 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_rename_author_name_theblog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='theblog',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theblog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
